[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Route our API path to the Netlify Function in prod & in `netlify dev`
[[redirects]]
  from = "/api/tmdb/*"
  to = "/.netlify/functions/tmdb"
  status = 200
